name: Trigger Automation Repo

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Playwright tests in Repo B
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.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 }}
          repository: Priya-299/CIScriptRun
          event-type: run-tests
